#+title: czm-preview.el: Convenience functions for compiling LaTeX
#+author: Paul Nelson

* Overview
This package provides convenience functions that support a LaTeX workflow where =latexmk= continuously compiles the document in the background.

* Configuration
Download this repository, install using =M-x package-install-file= (or package-vc-install, straight, elpaca, ...), and add something like the following to your [[https://www.emacswiki.org/emacs/InitFile][init file]]:
#+begin_src elisp
(use-package czm-tex-compile
    :bind
    ("C-c k" . czm-tex-compile)
    ("s-]" . czm-tex-compile-next-error)
    ("s-[" . czm-tex-compile-previous-error))
#+end_src
Replace the keybindings with whatever you prefer (or delete them and just run the commands via =M-x=).

* Usage

- If you run =czm-tex-compile= in a TeX buffer visiting "foo.tex", it starts an =eshell= buffer =*eshell-foo*= in the background that continuously compiles the current document.  Use =M-x customize-variable czm-tex-compile-command= to customize the compilation command.  If you run the same command again, then it switches to the =eshell= buffer.
- =czm-tex-compile-next-error= and =czm-tex-compile-previous-error= navigate the error and warning messages encountered in the log file produced by =latexmk=, jumping to the corresponding positions in the tex buffer.

That's all.  I prefer this workflow to the alternative in which one compiles the document manually via =TeX-command-master= (=C-c C-c=) and navigates the warning/error messages using =next-error= (=M-n=) and =previous-error (=M-p=).  It also gives a handy way to keep the .aux files up-to-date; I take advantage of this feature in the packages [[https://github.com/ultronozm/czm-preview.el][czm-preview.el]] and [[https://github.com/ultronozm/czm-tex-fold.el][czm-tex-fold.el]] to annotate the TeX buffer with label numbers.
