#+title: czm-tex-compile.el: Convenience functions for compiling LaTeX
#+author: Paul Nelson

* Overview
This package provides a minor mode where [[https://ctan.org/pkg/latexmk?lang=en][latexmk]] continuously compiles the document in the background and the errors/warnings are reported via [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Flymake.html][Flymake]].

* Configuration
Download this repository, install using =M-x package-install-file= (or package-vc-install, straight, elpaca, ...), and add something like the following to your [[https://www.emacswiki.org/emacs/InitFile][init file]]:
#+begin_src elisp
(use-package czm-tex-compile
    :bind
    ("C-c k" . czm-tex-compile-toggle))
#+end_src
Replace the keybinding with whatever you prefer (or delete it and just run the command via =M-x=).

You can tweak underlying the =latexmk= command via =M-x customize-variable czm-tex-compile-command=.

The command =czm-tex-compile-toggle= behaves the way that I prefer -- it enables both =czm-tex-compile-mode= and =flymake-mode=, restricting the backends for the latter to those coming from the former.  Depending upon your preferences, you may wish to write your own "wrapper" for =czm-tex-compile-mode= akin to =czm-tex-compile-toggle=.

The way the Flymake backend works, it will update only when the latexmk process reaches a "watching for changes" state and the buffer is unmodified.  The workflow to have errors and warnings reported is to save the file and wait a few seconds without editing.

That's all.  I prefer this workflow to the alternative in which one compiles the document manually via =TeX-command-master= (=C-c C-c=) and navigates the warning/error messages using =next-error= (=M-n=) and =previous-error= (=M-p=).  It also gives a handy way to keep the .aux files up-to-date; I take advantage of this feature in the packages [[https://github.com/ultronozm/czm-preview.el][czm-preview.el]] and [[https://github.com/ultronozm/czm-tex-fold.el][czm-tex-fold.el]] to annotate the TeX buffer with label numbers.
